#! /bin/sh

export GTK2_RC_FILES=/home/ryan/dotfiles/gtk/gtk-2.0/.gtkrc-2.0
export GTK_THEME="Nordic"

xset r rate 200 25

feh --bg-fill /home/ryan/dotfiles/wallpapers/selected
/home/ryan/.fehbg &

exec dwm
